apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Release.Name }}-traefik-dashboard
spec:
  entryPoints:
    - admin
  routes:
  - match: Host(`traefik.local`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))
    kind: Rule
    services:
    - name: {{ .Release.Name }}-traefik
      port: 8080
