// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: get_user.sql

package database

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, pass_hash, username
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.PassHash, &i.Username)
	return i, err
}
