// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Bill struct {
	ID           uuid.UUID
	UserID       sql.NullString
	Amount       sql.NullInt32
	CategoryName sql.NullString
	Ts           sql.NullTime
}

type Category struct {
	UserID string
	Name   string
}

type User struct {
	ID       string
	PassHash sql.NullString
	Username sql.NullString
}
