apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secrets
type: Opaque
data:
  primary-password: {{ .Values.postgres.primary.password | b64enc | quote }}
  replicator-password: {{ .Values.postgres.replica.password | b64enc | quote }}
  users-password: {{ .Values.postgres.users.password | b64enc | quote }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres-init
data:
  init-primary.sql: |
    {{ .Files.Get "files/init-primary.sql" | indent 4 }}
