// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BillMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Jwt           string                 `protobuf:"bytes,6,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BillMessage) Reset() {
	*x = BillMessage{}
	mi := &file_pkg_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BillMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BillMessage) ProtoMessage() {}

func (x *BillMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BillMessage.ProtoReflect.Descriptor instead.
func (*BillMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *BillMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BillMessage) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BillMessage) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *BillMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *BillMessage) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type CreateBillMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	UserId        string                 `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBillMessage) Reset() {
	*x = CreateBillMessage{}
	mi := &file_pkg_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBillMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBillMessage) ProtoMessage() {}

func (x *CreateBillMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBillMessage.ProtoReflect.Descriptor instead.
func (*CreateBillMessage) Descriptor() ([]byte, []int) {
	return file_pkg_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBillMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateBillMessage) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateBillMessage) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateBillMessage) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateBillMessage) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

var File_pkg_api_api_proto protoreflect.FileDescriptor

const file_pkg_api_api_proto_rawDesc = "" +
	"\n" +
	"\x11pkg/api/api.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xa1\x01\n" +
	"\vBillMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x10\n" +
	"\x03jwt\x18\x06 \x01(\tR\x03jwt\"\xae\x01\n" +
	"\x11CreateBillMessage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x128\n" +
	"\ttimestamp\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp2?\n" +
	"\x03Api\x128\n" +
	"\n" +
	"CreateBill\x12\x10.api.BillMessage\x1a\x16.google.protobuf.Empty\"\x00B\aZ\x05./apib\x06proto3"

var (
	file_pkg_api_api_proto_rawDescOnce sync.Once
	file_pkg_api_api_proto_rawDescData []byte
)

func file_pkg_api_api_proto_rawDescGZIP() []byte {
	file_pkg_api_api_proto_rawDescOnce.Do(func() {
		file_pkg_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_api_proto_rawDesc), len(file_pkg_api_api_proto_rawDesc)))
	})
	return file_pkg_api_api_proto_rawDescData
}

var file_pkg_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_api_proto_goTypes = []any{
	(*BillMessage)(nil),           // 0: api.BillMessage
	(*CreateBillMessage)(nil),     // 1: api.CreateBillMessage
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 3: google.protobuf.Empty
}
var file_pkg_api_api_proto_depIdxs = []int32{
	2, // 0: api.BillMessage.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: api.CreateBillMessage.timestamp:type_name -> google.protobuf.Timestamp
	0, // 2: api.Api.CreateBill:input_type -> api.BillMessage
	3, // 3: api.Api.CreateBill:output_type -> google.protobuf.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_api_api_proto_init() }
func file_pkg_api_api_proto_init() {
	if File_pkg_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_api_proto_rawDesc), len(file_pkg_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_api_proto_goTypes,
		DependencyIndexes: file_pkg_api_api_proto_depIdxs,
		MessageInfos:      file_pkg_api_api_proto_msgTypes,
	}.Build()
	File_pkg_api_api_proto = out.File
	file_pkg_api_api_proto_goTypes = nil
	file_pkg_api_api_proto_depIdxs = nil
}
