kafka:
  image: confluentinc/cp-kafka:latest
  storage: 1Gi

loadTester:
  image: harbor.devops-teta.ru/financial-tracker/load-tester:arm
  
postgres:
  primary:
    user: "ivang"
    password: "ivang"
    database: "db"
    storage: "1Gi"
  replica:
    password: "replicator_password"
    storage: "1Gi"
  users:
    user: "ivang"
    password: "ivang"
    database: "db"
    storage: "1Gi"

services:
  expenseReaderImage: "a4m1r04/expensereader:0.2.1"
  expensePublisherImage: "a4m1r04/expensepublisher:0.2.2"
  userServiceImage: "a4m1r04/userservice:0.2.1"
  expenseWriterImage: "a4m1r04/expensewriter:0.2.3"
