// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Bill struct {
	ID       int32
	Category string
	UserID   uuid.UUID
	Amount   float64
	Tmstmp   time.Time
	Name     string
}
