apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: website
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: website-app
  template:
    metadata:
      labels:
        app: website-app
    spec:
      containers:
        - name: website-app
          image: shulepusik/website:0.0.7
          imagePullPolicy: IfNotPresent