version: "2"
sql:
  - engine: "postgresql"
    schema: "../internal/database/migrations/*.up.sql"
    queries: "../internal/database/queries/*.sql"
    gen:
      go:
        package: "database"
        out: "../internal/database"
        sql_driver: "github.com/lib/pq"
