apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: envoy
  template:
    metadata:
      labels:
        app.kubernetes.io/component: envoy
    spec:
      containers:
      - name: envoy
        image: {{ .Values.envoy.image }}
        args: ["-c", "/etc/envoy/envoy.yaml"]
        ports:
        - containerPort: 1337
        volumeMounts:
        - name: envoy-config
          mountPath: /etc/envoy
      volumes:
      - name: envoy-config
        configMap:
          name: {{ .Release.Name }}-envoy-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-envoy
spec:
  type: LoadBalancer
  ports:
  - port: 1337
    targetPort: 1337
  selector:
    app.kubernetes.io/component: envoy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-envoy-config
data:
  envoy.yaml: |
    {{ .Files.Get "files/envoy.yaml" | indent 4 }}
