apiVersion: v1
kind: Service
metadata:
  name: kubelet
  namespace: kube-system
  labels:
    k8s-app: kubelet
spec:
  selector:
    node-role.kubernetes.io/master: ""    # или пустой селектор для всех нод
  ports:
    - name: https-metrics
      port: 10250
      targetPort: 10250
  type: ClusterIP
