apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-load-test
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: load-tester
            image: {{ .Values.loadTester.image }}
            imagePullPolicy: IfNotPresent
          restartPolicy: Never
