// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: pkg/api/api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_pkg_api_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_api_proto_rawDescGZIP(), []int{0}
}

func (x *GetReportRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

type GetReportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        map[string]float64     `protobuf:"bytes,1,rep,name=report,proto3" json:"report,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportResponse) Reset() {
	*x = GetReportResponse{}
	mi := &file_pkg_api_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResponse) ProtoMessage() {}

func (x *GetReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResponse.ProtoReflect.Descriptor instead.
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_api_proto_rawDescGZIP(), []int{1}
}

func (x *GetReportResponse) GetReport() map[string]float64 {
	if x != nil {
		return x.Report
	}
	return nil
}

type GetBillsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jwt           string                 `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillsRequest) Reset() {
	*x = GetBillsRequest{}
	mi := &file_pkg_api_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillsRequest) ProtoMessage() {}

func (x *GetBillsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillsRequest.ProtoReflect.Descriptor instead.
func (*GetBillsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_api_proto_rawDescGZIP(), []int{2}
}

func (x *GetBillsRequest) GetJwt() string {
	if x != nil {
		return x.Jwt
	}
	return ""
}

func (x *GetBillsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type Bill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        float64                `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Ts            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ts,proto3" json:"ts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bill) Reset() {
	*x = Bill{}
	mi := &file_pkg_api_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bill) ProtoMessage() {}

func (x *Bill) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bill.ProtoReflect.Descriptor instead.
func (*Bill) Descriptor() ([]byte, []int) {
	return file_pkg_api_api_proto_rawDescGZIP(), []int{3}
}

func (x *Bill) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bill) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Bill) GetTs() *timestamppb.Timestamp {
	if x != nil {
		return x.Ts
	}
	return nil
}

type GetBillsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bills         []*Bill                `protobuf:"bytes,1,rep,name=bills,proto3" json:"bills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBillsResponse) Reset() {
	*x = GetBillsResponse{}
	mi := &file_pkg_api_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBillsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBillsResponse) ProtoMessage() {}

func (x *GetBillsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBillsResponse.ProtoReflect.Descriptor instead.
func (*GetBillsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetBillsResponse) GetBills() []*Bill {
	if x != nil {
		return x.Bills
	}
	return nil
}

var File_pkg_api_api_proto protoreflect.FileDescriptor

const file_pkg_api_api_proto_rawDesc = "" +
	"\n" +
	"\x11pkg/api/api.proto\x12\x03api\x1a\x1fgoogle/protobuf/timestamp.proto\"$\n" +
	"\x10GetReportRequest\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\"\x8a\x01\n" +
	"\x11GetReportResponse\x12:\n" +
	"\x06report\x18\x01 \x03(\v2\".api.GetReportResponse.ReportEntryR\x06report\x1a9\n" +
	"\vReportEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\"?\n" +
	"\x0fGetBillsRequest\x12\x10\n" +
	"\x03jwt\x18\x01 \x01(\tR\x03jwt\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\"^\n" +
	"\x04Bill\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x02ts\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x02ts\"3\n" +
	"\x10GetBillsResponse\x12\x1f\n" +
	"\x05bills\x18\x01 \x03(\v2\t.api.BillR\x05bills2~\n" +
	"\x03Api\x12<\n" +
	"\tGetReport\x12\x15.api.GetReportRequest\x1a\x16.api.GetReportResponse\"\x00\x129\n" +
	"\bGetBills\x12\x14.api.GetBillsRequest\x1a\x15.api.GetBillsResponse\"\x00B\aZ\x05./apib\x06proto3"

var (
	file_pkg_api_api_proto_rawDescOnce sync.Once
	file_pkg_api_api_proto_rawDescData []byte
)

func file_pkg_api_api_proto_rawDescGZIP() []byte {
	file_pkg_api_api_proto_rawDescOnce.Do(func() {
		file_pkg_api_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_api_proto_rawDesc), len(file_pkg_api_api_proto_rawDesc)))
	})
	return file_pkg_api_api_proto_rawDescData
}

var file_pkg_api_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_api_api_proto_goTypes = []any{
	(*GetReportRequest)(nil),      // 0: api.GetReportRequest
	(*GetReportResponse)(nil),     // 1: api.GetReportResponse
	(*GetBillsRequest)(nil),       // 2: api.GetBillsRequest
	(*Bill)(nil),                  // 3: api.Bill
	(*GetBillsResponse)(nil),      // 4: api.GetBillsResponse
	nil,                           // 5: api.GetReportResponse.ReportEntry
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_pkg_api_api_proto_depIdxs = []int32{
	5, // 0: api.GetReportResponse.report:type_name -> api.GetReportResponse.ReportEntry
	6, // 1: api.Bill.ts:type_name -> google.protobuf.Timestamp
	3, // 2: api.GetBillsResponse.bills:type_name -> api.Bill
	0, // 3: api.Api.GetReport:input_type -> api.GetReportRequest
	2, // 4: api.Api.GetBills:input_type -> api.GetBillsRequest
	1, // 5: api.Api.GetReport:output_type -> api.GetReportResponse
	4, // 6: api.Api.GetBills:output_type -> api.GetBillsResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pkg_api_api_proto_init() }
func file_pkg_api_api_proto_init() {
	if File_pkg_api_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_api_proto_rawDesc), len(file_pkg_api_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_api_proto_goTypes,
		DependencyIndexes: file_pkg_api_api_proto_depIdxs,
		MessageInfos:      file_pkg_api_api_proto_msgTypes,
	}.Build()
	File_pkg_api_api_proto = out.File
	file_pkg_api_api_proto_goTypes = nil
	file_pkg_api_api_proto_depIdxs = nil
}
