apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-load-test
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        spec:
          containers:
          - name: load-tester
            image: {{ .Values.loadTester.image }}
            imagePullPolicy: IfNotPresent
            env:
            - name: USER_SERVICE_ADDR
              value: {{ .Release.Name }}-user-service:7777
            - name: PUBLISHER_ADDR
              value: {{ .Release.Name }}-expense-publisher:7777
            - name: READER_ADDR
              value: {{ .Release.Name }}-expense-reader:7777
          restartPolicy: Never
